name: Deploy Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:.
          docker push ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:
            docker stop app-node || true
            docker rm app-node || true
            docker run -d --name app-node -p 8104:8104 \
              -e PORT=8104 \
              ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:
